### ISSUE TITLE
Doesn't deal well with large numbers of input files

### ISSUE THREAD

**Issue by wwood** [wwood/singlem#1]
It appears to work, but is a bit slow because the second graftm step acts as a double for loop. It would be better as a single for loop looping over gpkgs, and give all the input files to graftm at once. This way the pplacer tree doesn't need to be read in over and over.

**Comment by xvazquezc** [comment]
Another problem with multiple input files: does not recognise asterisk as wildcard in the middle of the filename (i.e. `028-LFA_*.fastq.gz`):
`06/22/2016 03:46:39 PM INFO: Using as input 1 different sequence files e.g. 028-LFA_*.fastq.gz
06/22/2016 03:46:40 PM INFO: Searching for reads matching 30 different protein HMMs
Traceback (most recent call last):
  File "/home/z3382651/bin/singlem/bin/singlem", line 327, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 108, in run
    search_result = self._search(hmms, forward_read_files)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 520, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 512, in run
    extern.run(cmd)
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/extern/__init__.py", line 30, in run
    stdout)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 12 --forward 028-LFA_*.fastq.gz --search_only --search_hmm_files /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE/graftmyMs8Yt_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE/graftmTfJ6Ql_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.19.ribosomal_protein_S12_S23.gpkg.spkg/4.19.ribosomal_protein_S12_S23/graftm0jUili_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.19.ribosomal_protein_S12_S23.gpkg.spkg/4.19.ribosomal_protein_S12_S23/graftmkDMHbw_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.18.ribosomal_protein_S10_rpsJ.gpkg.spkg/4.18.ribosomal_protein_S10_rpsJ/graftm__FSnc_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.18.ribosomal_protein_S10_rpsJ.gpkg.spkg/4.18.ribosomal_protein_S10_rpsJ/graftmjrbRZd_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.15.ribosomal_protein_S2_rpsB.gpkg.spkg/4.15.ribosomal_protein_S2_rpsB/graftmwIz0De_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.15.ribosomal_protein_S2_rpsB.gpkg.spkg/4.15.ribosomal_protein_S2_rpsB/graftmKdLlZz_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.10.ribosomal_protein_L6_rplF.gpkg.spkg/4.10.ribosomal_protein_L6_rplF/graftmQNplv3_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.10.ribosomal_protein_L6_rplF.gpkg.spkg/4.10.ribosomal_protein_L6_rplF/graftmmXEyAR_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.08.ribosomal_protein_L3_rplC.gpkg.spkg/4.08.ribosomal_protein_L3_rplC/graftm9H24vO_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.08.ribosomal_protein_L3_rplC.gpkg.spkg/4.08.ribosomal_protein_L3_rplC/graftmTpYyQM_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.21.ribosomal_protein_S19_rpsS.gpkg.spkg/4.21.ribosomal_protein_S19_rpsS/graftmmuWy_P_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.21.ribosomal_protein_S19_rpsS.gpkg.spkg/4.21.ribosomal_protein_S19_rpsS/graftmK2Qzj9_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.12.ribosomal_protein_L11_rplK.gpkg.spkg/4.12.ribosomal_protein_L11_rplK/graftmsR8moo_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.12.ribosomal_protein_L11_rplK.gpkg.spkg/4.12.ribosomal_protein_L11_rplK/graftmgyqgXl_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.07.ribosomal_protein_L2_rplB.gpkg.spkg/4.07.ribosomal_protein_L2_rplB/graftmIi9ipp_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.07.ribosomal_protein_L2_rplB.gpkg.spkg/4.07.ribosomal_protein_L2_rplB/graftmbdiWA2_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.13.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/4.13.ribosomal_protein_L14b_L23e_rplN/graftmzhRzmq_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.13.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/4.13.ribosomal_protein_L14b_L23e_rplN/graftmnYiuII_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.16.ribosomal_protein_S5.gpkg.spkg/4.16.ribosomal_protein_S5/graftmqKtHTs_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.16.ribosomal_protein_S5.gpkg.spkg/4.16.ribosomal_protein_S5/graftmpuZ5Di_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.11.ribosomal_protein_L10.gpkg.spkg/4.11.ribosomal_protein_L10/graftmJ13IRm_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.11.ribosomal_protein_L10.gpkg.spkg/4.11.ribosomal_protein_L10/graftmYvtMa9_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.14.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/4.14.ribosomal_protein_L16_L10E_rplP/graftmEN3gBL_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.14.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/4.14.ribosomal_protein_L16_L10E_rplP/graftms5tUZU_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.20.ribosomal_protein_S15P_S13e.gpkg.spkg/4.20.ribosomal_protein_S15P_S13e/graftme1EtU3_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.20.ribosomal_protein_S15P_S13e.gpkg.spkg/4.20.ribosomal_protein_S15P_S13e/graftmT1CGO9_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.17.ribosomal_protein_S7.gpkg.spkg/4.17.ribosomal_protein_S7/graftmhq3Ygj_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.17.ribosomal_protein_S7.gpkg.spkg/4.17.ribosomal_protein_S7/graftmNHyRbc_search.hmm --output_directory /dev/shm/tmp6WHKwH/graftm_protein_search --aln_hmm_file /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE/graftmyMs8Yt_search.hmm  returned non-zero exit status 1.
STDERR was: 06/22/2016 03:47:27 PM ERROR: The file '028-LFA_*.fastq.gz' does not appear to exist, stopping
STDOUT was: `


It didn't happen when I wrote the asterisk at the beginning though (`*.fastq.gz`). Or at least it didn't crushed yet:
`06/22/2016 04:01:35 PM INFO: Using as input 12 different sequence files e.g. 028-LFA_all_raw.fastq.gz
06/22/2016 04:01:35 PM INFO: Searching for reads matching 30 different protein HMMs`

**Comment by wwood** [comment]
Thanks for trying SingleM.

Also thanks for reminding me about this issue, since I recently fixed it and can close it.

re. the asterisks, I believe wildcard expansion is usually handled by the shell (e.g. bash), and then the expanded set of arguments are provided to the program (singlem) as if they were typed out in their entirety. What is the command line you are running?

**Comment by xvazquezc** [comment]
This works:
```
singlem pipe --sequences *.fastq.gz --otu_table 028-LFA_otu_table.csv --threads 12
```
This doesn't:
```
singlem pipe --sequences 028-LFA_*.fastq.gz --otu_table 028-LFA_otu_table.csv --threads 12
```

**Comment by wwood** [comment]
Does this?
```
ls 28-LFA_*.fastq.gz
```

**Comment by wwood** [comment]
oh sorry I mean
```
ls 028-LFA_*.fastq.gz
```

**Comment by xvazquezc** [comment]
My bad, I think the job script was pointing to an old folder... (note to self: reuse with care)

**Comment by wwood** [comment]
No problem. Let me know if you come across any other issues with SingleM or if you have feedback.

**Comment by xvazquezc** [comment]
Sure. 
By the way, do you have any rough estimates about how much memory and how long does ```singlem pipe``` take to run?
And just to be sure, it only take forward reads, isn't it? because I got this error message, but in the GitHub front page doesn't say anything about it
```
Multiple sequences found with the same ID. The input sequences are either ill formated or are interleaved. If you provided GraftM with an interleaved sequence file, please split them into forward and reverse reads, and provide to the the appropriate flags (--forward, --reverse). Otherwise, it appears that you have provided sequences with redundant IDs. GraftM doesn't know how to deal with these, so please remove/rename sequences with duplicate keys.
```

**Comment by wwood** [comment]
I'm afraid I do not have any hard numbers on memory or CPU usage, this depends on which singlem packages are used. Anecdotally (and as partly a guess) it takes about ~30 mins with 40 threads given a regular size metagenome. I'm not sure about the memory usage, but it will be a lot less than running GraftM on a 16S tree. If you are having issues with memory or CPU you can use `--assignment_method diamond` or `diamond_example` so that the memory-intensive pplacer step is skipped.

You can run it on the forward and reverse reads separately, and concatenate the OTU tables - that gives effectively the same result as if they were done together (probably best to trust the forward read taxonomy over the reverse since it is probably better quality). They should return broadly similar community profiles, depending on what you are looking for.
