### ISSUE TITLE
No smafa-naive / nucleotide sequence index DB found

### ISSUE THREAD

**Issue by ricardoamj** [wwood/singlem#118]
Hello, I like singlem, thanks for developing it. I installed the conda version and ran in the following command:  

singlem pipe -1 /tmp/Sample_1u_001.R1.fq.gz -2 /tmp/Sample_1u_001.R2.fq.gz -p fildes1.profile.txt --threads 10 

and I received the following message 

12/16/2022 02:44:14 PM INFO: SingleM v1.0.0beta4
12/16/2022 02:44:14 PM INFO: Retrieval successful. Location of backpack is: /home/ricardom/singlem/bin/singlem.data/S3.0.5.metapackage20220806.smpkg.zb
12/16/2022 02:44:14 PM INFO: Loaded 59 SingleM packages
12/16/2022 02:44:14 PM INFO: Using as input 1 different pairs of sequence files e.g. /tmp/Sample_1u_001.R1.fq.gz & /tmp/Sample_1u_001.R2.fq.gz
12/16/2022 02:44:14 PM INFO: Filtering sequence files through DIAMOND blastx
12/16/2022 03:04:19 PM INFO: Finished DIAMOND prefilter phase
12/16/2022 03:04:19 PM INFO: Assigning sequences to SingleM packages with DIAMOND ..
12/16/2022 03:04:56 PM INFO: Running taxonomic assignment ..
12/16/2022 03:04:56 PM INFO: Assigning taxonomy by singlem query ..
/home/ricardom/anaconda3/envs/singlem/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
12/16/2022 03:05:01 PM INFO: Searching with SMAFA NAIVE by nucleotide sequence ..
12/16/2022 03:05:01 PM WARNING: No smafa-naive / nucleotide sequence index DB found for S3.10.ribosomal_protein_S19_rpsS
Traceback (most recent call last):
  File "/home/ricardom/./singlem/bin/singlem", line 572, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/ricardom/singlem/bin/../singlem/pipe.py", line 63, in run
    otu_table_object = self.run_to_otu_table(**kwargs)
  File "/home/ricardom/singlem/bin/../singlem/pipe.py", line 421, in run_to_otu_table
    otu_table_object = self.assign_taxonomy_and_process(
  File "/home/ricardom/singlem/bin/../singlem/pipe.py", line 456, in assign_taxonomy_and_process
    assignment_result = self._assign_taxonomy(
  File "/home/ricardom/singlem/bin/../singlem/pipe.py", line 1173, in _assign_taxonomy
    query_based_assignment_result = PipeTaxonomyAssignerByQuery().assign_taxonomy(
  File "/home/ricardom/singlem/bin/../singlem/pipe_taxonomy_assigner_by_query.py", line 95, in assign_taxonomy
    query_single_set(queries[0], 0)
  File "/home/ricardom/singlem/bin/../singlem/pipe_taxonomy_assigner_by_query.py", line 78, in query_single_set
    for hit in querier.query_with_queries(queries, sdb, 3, method, SequenceDatabase.NUCLEOTIDE_TYPE, 1, None, False, None):
  File "/home/ricardom/singlem/bin/../singlem/querier.py", line 347, in query_by_sequence_similarity_with_smafa_naive
    raise Exception("The marker '{}' does not appear to be 'smafa-naive/{}' indexed in the singlem db".format(marker, sequence_type))
Exception: The marker 'S3.10.ribosomal_protein_S19_rpsS' does not appear to be 'smafa-naive/nucleotide' indexed in the singlem db

i ran in Linux lebserver 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

could you please help me, thanks

**Comment by wwood** [comment]
Hi,

Thanks for the kind words.

This is a consequence of me lazily doing dev work in the main branch. Trying checking out the last tag or using the docker version.

Am actively working on fixing this.
ben

**Comment by ricardoamj** [comment]
Thanks for your attention, I ran version 0.13.2 and there were no problems. I don't have root access to install in docker.

Regards

**Comment by wwood** [comment]
No problem. I strongly suggest using 1.0.0beta4 though from github. It's a tag but not a release. You'll need to setup the env through conda, but not singlem itself

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by wwood** [comment]
Hi,

I've moved the unstable coding to the dev branch, and so the main branch should work now. So the "Installation via Github, with conda environment dependencies" instructions, which I suppose you followed, should work again now.

Closing this now, let me know if you run into any difficulties.
