### ISSUE TITLE
unifrac files for beta diversity

### ISSUE THREAD

**Issue by xvazquezc** [wwood/singlem#12]
Hi,
I've followed the steps for calculating beta diversity `singlem summarise --input_otu_table otu_table.csv --unifrac otu_table.unifrac` but the output is not a single `otu_table.unifrac` but 15, one for each ribosomal protein.
Is this expected? I ask because that don't seem very clear in the front-page instructions.
Thank you,
Xabi

**Comment by wwood** [comment]
Yes it is expected to get 15 tables. Unfortunately getting a single profile combined out of all 15 genes is non-trivial (e.g. what is 2 closely related lineages share some window sequences but not others?) . I'd calculate beta diversity using a few different unifrac files - hopefully the choice of gene used for beta diversity calculation matters little for your question.

I'll take a stab at fixing the readme - I agree it is quite unclear on this point.

**Comment by wwood** [comment]
I hope this has now been made clear at https://github.com/wwood/singlem#calculating-beta-diversity-between-samples - if not let me know. I'm closing this issue now given the passing of time, but if you feel otherwise feel free to comment further. Thanks.
