### ISSUE TITLE
Problems in updating the default metapackage by using regenerate function

### ISSUE THREAD

**Issue by houjialin** [wwood/singlem#121]
Hi, Ben, 
SingleM is a very nice tool, thanks for your developing. I've successfully get the metagenome taxonomic profile with the default metapackage. Now, I want to update the default metapackage by adding several new MAGs with novel taxonomic information that are not included in the current GTDB database. So I decided to use the `regenerate` function but met some problems.

My input files are three ribosomal_protein_L2_rplB protein sequences and corresponding taxonomic information of three MAGs. Their contents just like:
- Sequences.faa
```
>QDN1_bins_089
MGKNIRVQRRGRGSSTFKATTHKRVAPSRYVPLSTTKGDEPKLAIIEELLHEPGRGSPLLKARAERGIFHLVAPEGVFVGQELQFGEKASIAAGNFLPLSEIPSGTYVCNLELSPGDGGKIAKASGTFATVVAQTPEGVQVRLPSKKSVYLNPKCRATIGVISGSGRTGKPFAKAGKRSAWLKSKGRIYPRSKGVAMNAASHPHGGGAHKTQSLKPTTVSRNAPPGQKVGLIAARQSGRKQRRR*
>DVMM_Bin_selected_10_contigs.id.723
MGKRIRVQRRGRGSSTFKGSTHKRVAPSRYTPLSKTEGDEPKRAVVEELLHEPGRGSPLIKARADRGVFHLVAPEGVSVGQELQFGENASIATGNFLPLSEIPSGTYVCNLELSPGDGGKIAKSSGTYATVVAQTPEGIQVRLPSKKSVYLNPKCRATIGVVSGSGRTGKPFAKAGKRAKWMKSKGKVYPRSKGVAMVPASHPHGGGAHKSSSLRPTTVSRTAPPGQKVGLIAARQSGRKQRRR*
>DVMM_MetaBat_3k.txt.533
MGKRIRVQRRGKGSPTFKASTHKRVAPSKYPSLSNLKESSTILVEDLVHDPGRGAPLLKGRLEDQIVHIVAPEGVSTGQEVFLGRQAPLAIGSILPLQQIPPGTIVCNLERSPGDGGKIAKASGTYASVVTHTSDGILVRLPSKRTKYFHPQCRATIGVISGAGRVMKPFVKAGNIHHWKTAKGKMYPTTKGVAMVPAYHPHGGGAHKSSSLRPTTVSRTTPPGRKVGLIAARQSGRAKRRRTRA*
```
- Taxonomy.txt
```
DVMM_Bin_selected_10_contigs.id.723 d__Archaea;p__Thermoproteota;c__Bathyarchaeia;o__Mazu;f__f1;g__g1;s__s1
DVMM_MetaBat_3k.txt.533 d__Archaea;p__Thermoproteota;c__Bathyarchaeia;o__Mazu;f__f2;g__g2;s__s2
QDN1_bins_089   d__Archaea;p__Thermoproteota;c__Bathyarchaeia;o__Mazu;f__f3;g__g3;s__s3
```
And my command is 

```
singlem regenerate --input-singlem-package ~/Software/singlem-main/data/dbs/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/S3.1.ribosomal_protein_L2_rplB.spkg/ --output-singlem-package S3.1.ribosomal_protein_L2_rplB.updated.spkg/ --input-sequences ./L2_rplB.faa --input-taxonomy ./L2_rplB.taxonomy.txt --sequence-prefix ribosomal_protein_L2_rplB --no-further-euks
```
After running, I got the updated package but the problem is it only contains the three MAGs' sequences and taxonomic information (all other GTDB MAGs are missed). Could you help me solve this problem ?

**Comment by wwood** [comment]
Hi,

The regenerate function is really an expert-only mode, hence your issues. I wonder if it might be worth talking through a potential collaboration on this? I don't know who you are but looks like an interesting taxon string... email me if interested.

Sorry there's no straightforward solution.
ben
