### ISSUE TITLE
Updated release?

### ISSUE THREAD

**Issue by linsalrob** [wwood/singlem#125]
I have singlem version 0.13.2 (which I think is the latest), but it doesn't have a data option:

```bash
$ singlem --version
0.13.2
```

and then 

```
$ singlem data
usage: singlem [-h] [--debug] [--version] [--quiet]
               {pipe,seqs,makedb,query,summarise,renew,create,get_tree,regenerate,appraise,chance}
               ...
singlem: error: argument subparser_name: invalid choice: 'data' (choose from 'pipe', 'seqs', 'makedb', 'query', 'summarise', 'renew', 'create', 'get_tree', 'regenerate', 'appraise', 'chance')
```

Is this the latest release?

**Comment by wwood** [comment]
Hi Rob,

No, the newest you'll have to get via git clone a tag I'm afraid. 1.0beta5 I think. Thanks for sticking with it.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Rob Edwards ***@***.***>
Sent: Monday, March 27, 2023 9:15:05 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] Updated release? (Issue #125)


I have singlem version 0.13.2 (which I think is the latest), but it doesn't have a data option:

$ singlem --version
0.13.2

and then

$ singlem data
usage: singlem [-h] [--debug] [--version] [--quiet]
               {pipe,seqs,makedb,query,summarise,renew,create,get_tree,regenerate,appraise,chance}
               ...
singlem: error: argument subparser_name: invalid choice: 'data' (choose from 'pipe', 'seqs', 'makedb', 'query', 'summarise', 'renew', 'create', 'get_tree', 'regenerate', 'appraise', 'chance')


Is this the latest release?

―
