### ISSUE TITLE
Error: metapackage sqlite3 database

### ISSUE THREAD

**Issue by kalonji08** [wwood/singlem#126]
Hello I have the following error:
Traceback (most recent call last):
  File "/home/kalonjilab2/singlem/bin/singlem", line 593, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/kalonjilab2/singlem/bin/../singlem/pipe.py", line 77, in run
    Condenser().condense(
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 57, in condense
    to_yield = list(to_yield)
               ^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 105, in _condense_to_otu_table
    yield self._condense_a_sample(sample, sample_otus, markers, target_domains, trim_percent, min_taxon_coverage,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 128, in _condense_a_sample
    self._convert_diamond_best_hit_ids_to_taxonomies(metapackage, sample_otus)
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 184, in _convert_diamond_best_hit_ids_to_taxonomies
    sequence_id_to_taxon = metapackage.get_taxonomy_of_reads(sequence_ids)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/metapackage.py", line 372, in get_taxonomy_of_reads
    return store.get_taxonomy_of_reads(read_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/metapackage_read_name_store.py", line 70, in get_taxonomy_of_reads
    raise Exception("Not all read names found in metapackage sqlite3 database")
Exception: Not all read names found in metapackage sqlite3 database

**Comment by wwood** [comment]
Hi,

That's an odd one, can you please post what command line you used? The full set of logging output, not just the error, would help diagnose I think.

**Comment by kalonji08** [comment]
Hi apologies for the late response.  I will try and re-run to get the full output. here is the code:

singlem pipe -1 /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/P1_S7_L001_R1_001.fastq.gz -2 /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/P1_S7_L001_R2_001.fastq.gz -p results/P1output.profile.tsv --taxonomic-profile-krona results/P1-OTU.profile.html --threads 35

**Comment by kalonji08** [comment]
just tried it and this time it worked! 



04/25/2023 09:35:26 AM INFO: Finished
04/25/2023 09:35:26 AM INFO: Writing Krona to results/P1-OTU.profile.html
04/25/2023 09:35:26 AM INFO: Removing off-target OTUs from P1_S7_L001_R1_001
04/25/2023 09:35:26 AM INFO: Found 26536.37 assigned and 137.37 unassigned OTU coverage units
04/25/2023 09:35:26 AM INFO: After removing off-target OTUs, found 21833.06 assigned and 0.00 unassigned OTU coverage units
04/25/2023 09:35:26 AM INFO: Total coverage by query: 20959.00546487835
04/25/2023 09:35:26 AM INFO: Total coverage by diamond: 874.0574678239011
04/25/2023 09:35:26 AM INFO: Applying species-wise expectation maximization algorithm to OTU table
04/25/2023 09:35:26 AM INFO: Found 18 species uniquely hitting >= 10 marker genes
04/25/2023 09:35:27 AM INFO: Species-wise EM converged in 42 steps
04/25/2023 09:35:27 AM INFO: Gathering equivalence classes
04/25/2023 09:35:27 AM INFO: Demultiplexing OTU table
04/25/2023 09:35:27 AM INFO: Finished expectation maximization
04/25/2023 09:35:27 AM INFO: Converting DIAMOND IDs to taxons
04/25/2023 09:36:19 AM INFO: Converted 393 Diamond-assigned OTU taxon_ids to taxon strings
04/25/2023 09:36:19 AM INFO: Applying genus-wise expectation maximization algorithm to OTU table
04/25/2023 09:36:29 AM INFO: Genus-wise EM converged in 87 steps
04/25/2023 09:36:29 AM INFO: Gathering equivalence classes
04/25/2023 09:36:29 AM INFO: Demultiplexing OTU table
04/25/2023 09:36:29 AM INFO: Finished genus expectation maximization
04/25/2023 09:36:29 AM INFO: Total coverage: 21833.062932702363
04/25/2023 09:36:29 AM INFO: Taxonomic level coverage:
04/25/2023 09:36:29 AM INFO: kingdom:   0.30%   1 taxons
04/25/2023 09:36:29 AM INFO: phylum:    0.13%   1 taxons
04/25/2023 09:36:29 AM INFO: class:     0.13%   2 taxons
04/25/2023 09:36:29 AM INFO: order:     0.20%   2 taxons
04/25/2023 09:36:29 AM INFO: family:    1.10%   6 taxons
04/25/2023 09:36:29 AM INFO: genus:     10.64%  11 taxons
04/25/2023 09:36:29 AM INFO: species:   87.51%  30 taxons
04/25/2023 09:36:29 AM INFO: Writing taxonomic profile to results/P1output.profile.tsv
04/25/2023 09:36:29 AM INFO: Finished condense

**Comment by wwood** [comment]
Oh good. Let me know if you have any further problems

**Comment by kalonji08** [comment]
Seems like i have found the sample that gave me the error:
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2204:29405:4633
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2204:19262:17785
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2210:27389:33677
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2227:6108:28166
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2272:12554:14967
04/25/2023 11:39:51 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2129:21133:22748
04/25/2023 11:39:51 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2144:10276:32690
04/25/2023 11:39:51 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2147:24659:4210
04/25/2023 11:39:51 AM INFO: Finished
04/25/2023 11:39:51 AM INFO: Writing Krona to results/PRO-OTU.profile.html
04/25/2023 11:39:51 AM INFO: Removing off-target OTUs from PRO_S2_L001_R1_001
04/25/2023 11:39:51 AM INFO: Found 47434.87 assigned and 178.32 unassigned OTU coverage units
04/25/2023 11:39:51 AM INFO: After removing off-target OTUs, found 39576.57 assigned and 0.00 unassigned OTU coverage units
04/25/2023 11:39:51 AM INFO: Total coverage by query: 38309.92911655526
04/25/2023 11:39:51 AM INFO: Total coverage by diamond: 1266.6359009656587
04/25/2023 11:39:51 AM INFO: Applying species-wise expectation maximization algorithm to OTU table
04/25/2023 11:39:51 AM INFO: Found 13 species uniquely hitting >= 10 marker genes
04/25/2023 11:39:52 AM INFO: Species-wise EM converged in 64 steps
04/25/2023 11:39:52 AM INFO: Gathering equivalence classes
04/25/2023 11:39:52 AM INFO: Demultiplexing OTU table
04/25/2023 11:39:52 AM INFO: Finished expectation maximization
04/25/2023 11:39:52 AM INFO: Converting DIAMOND IDs to taxons
Traceback (most recent call last):
  File "/home/kalonjilab2/singlem/bin/singlem", line 593, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/kalonjilab2/singlem/bin/../singlem/pipe.py", line 77, in run
    Condenser().condense(
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 57, in condense
    to_yield = list(to_yield)
               ^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 105, in _condense_to_otu_table
    yield self._condense_a_sample(sample, sample_otus, markers, target_domains, trim_percent, min_taxon_coverage, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 128, in _condense_a_sample
    self._convert_diamond_best_hit_ids_to_taxonomies(metapackage, sample_otus)
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 184, in _convert_diamond_best_hit_ids_to_taxonomies
    sequence_id_to_taxon = metapackage.get_taxonomy_of_reads(sequence_ids)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/metapackage.py", line 372, in get_taxonomy_of_reads
    return store.get_taxonomy_of_reads(read_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/metapackage_read_name_store.py", line 70, in get_taxonomy_of_reads
    raise Exception("Not all read names found in metapackage sqlite3 database")
Exception: Not all read names found in metapackage sqlite3 database

**Comment by kalonji08** [comment]
For this specific sample, Everything runs until here:
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2204:29405:4633
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2204:19262:17785
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2210:27389:33677
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2227:6108:28166
04/25/2023 11:39:50 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2272:12554:14967
04/25/2023 11:39:51 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2129:21133:22748
04/25/2023 11:39:51 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2144:10276:32690
04/25/2023 11:39:51 AM WARNING: Unexpected lack (or >1 found) of assignment method for read name A00769:84:H7YWTDRX2:1:2147:24659:4210
04/25/2023 11:39:51 AM INFO: Finished
04/25/2023 11:39:51 AM INFO: Writing Krona to results/PRO-OTU.profile.html
04/25/2023 11:39:51 AM INFO: Removing off-target OTUs from PRO_S2_L001_R1_001
04/25/2023 11:39:51 AM INFO: Found 47434.87 assigned and 178.32 unassigned OTU coverage units
04/25/2023 11:39:51 AM INFO: After removing off-target OTUs, found 39576.57 assigned and 0.00 unassigned OTU coverage units
04/25/2023 11:39:51 AM INFO: Total coverage by query: 38309.92911655526
04/25/2023 11:39:51 AM INFO: Total coverage by diamond: 1266.6359009656587
04/25/2023 11:39:51 AM INFO: Applying species-wise expectation maximization algorithm to OTU table
04/25/2023 11:39:51 AM INFO: Found 13 species uniquely hitting >= 10 marker genes
04/25/2023 11:39:52 AM INFO: Species-wise EM converged in 64 steps
04/25/2023 11:39:52 AM INFO: Gathering equivalence classes
04/25/2023 11:39:52 AM INFO: Demultiplexing OTU table
04/25/2023 11:39:52 AM INFO: Finished expectation maximization
04/25/2023 11:39:52 AM INFO: Converting DIAMOND IDs to taxons
Traceback (most recent call last):
  File "/home/kalonjilab2/singlem/bin/singlem", line 593, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/kalonjilab2/singlem/bin/../singlem/pipe.py", line 77, in run
    Condenser().condense(
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 57, in condense
    to_yield = list(to_yield)
               ^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 105, in _condense_to_otu_table
    yield self._condense_a_sample(sample, sample_otus, markers, target_domains, trim_percent, min_taxon_coverage, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 128, in _condense_a_sample
    self._convert_diamond_best_hit_ids_to_taxonomies(metapackage, sample_otus)
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 184, in _convert_diamond_best_hit_ids_to_taxonomies
    sequence_id_to_taxon = metapackage.get_taxonomy_of_reads(sequence_ids)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/metapackage.py", line 372, in get_taxonomy_of_reads
    return store.get_taxonomy_of_reads(read_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/metapackage_read_name_store.py", line 70, in get_taxonomy_of_reads
    raise Exception("Not all read names found in metapackage sqlite3 database")
Exception: Not all read names found in metapackage sqlite3 database

**Comment by kalonji08** [comment]
Here is the code: 
singlem pipe -1 /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/PRO_S2_L001_R1_001.fastq.gz -2 /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/PRO_S2_L001_R2_001.fastq.gz -p results/PROoutput.profile.tsv --taxonomic-profile-krona results/PRO-OTU.profile.html --threads 35

**Comment by wwood** [comment]
Hmm, can you run with --no-assign-taxonomy and --archive-otu-table and send me the archive please? Either via email or just attached here.

Thanks.

**Comment by kalonji08** [comment]
No problem 
Here is the archive file i gave the zip extension but you can change it 


[arcivefile.zip](https://github.com/wwood/singlem/files/11322173/arcivefile.zip)

**Comment by kalonji08** [comment]
This was the output

 singlem pipe -1 /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/PRO_S2_L001_R1_001.fastq.gz -2 /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/PRO_S2_L001_R2_001.fastq.gz -p results/PROoutput.profile.tsv --taxonomic-profile-krona results/PRO-OTU.profile.html --threads 35 --no-assign-taxonomy --archive-otu-table arcivePRO
04/25/2023 01:43:03 PM INFO: SingleM v1.0.0beta5
04/25/2023 01:43:03 PM INFO: Retrieval successful. Location of backpack is: /media/kalonjilab2/kalonjiPhD/singleM-db/S3.1.0.metapackage_20221209.smpkg.zb
04/25/2023 01:43:03 PM INFO: Loaded 59 SingleM packages
04/25/2023 01:43:03 PM INFO: Using as input 1 different pairs of sequence files e.g. /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/PRO_S2_L001_R1_001.fastq.gz & /media/kalonjilab2/KalonjiBCK1/Raw_Metagenomes/PRO_S2_L001_R2_001.fastq.gz
04/25/2023 01:43:03 PM INFO: Filtering sequence files through DIAMOND blastx
04/25/2023 01:49:42 PM INFO: Finished DIAMOND prefilter phase
04/25/2023 01:49:42 PM INFO: Assigning sequences to SingleM packages with DIAMOND ..
04/25/2023 01:49:55 PM INFO: Finished
04/25/2023 01:49:55 PM INFO: Writing Krona to results/PRO-OTU.profile.html
04/25/2023 01:49:55 PM INFO: Removing off-target OTUs from PRO_S2_L001_R1_001
04/25/2023 01:49:55 PM INFO: Found 47613.20 assigned and 0.00 unassigned OTU coverage units
Traceback (most recent call last):
  File "/home/kalonjilab2/singlem/bin/singlem", line 593, in <module>
    singlem.pipe.SearchPipe().run(
  File "/home/kalonjilab2/singlem/bin/../singlem/pipe.py", line 77, in run
    Condenser().condense(
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 57, in condense
    to_yield = list(to_yield)
               ^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 105, in _condense_to_otu_table
    yield self._condense_a_sample(sample, sample_otus, markers, target_domains, trim_percent, min_taxon_coverage, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 116, in _condense_a_sample
    sample_otus = self._remove_off_target_otus(sample_otus, markers)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 352, in _remove_off_target_otus
    table.data = [otu.data for otu in sample_otus if \
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 353, in <listcomp>
    self._is_targeted_by_marker(otu, otu.taxonomy_array(), markers) and \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kalonjilab2/singlem/bin/../singlem/condense.py", line 363, in _is_targeted_by_marker
    if tax_split[0] != 'Root':
       ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by kalonji08** [comment]
Hi @wwood i wanted to find out if you have any updates on this?

**Comment by wwood** [comment]
Sorry for slow response. On holiday ATM will take a look when back.

**Comment by wwood** [comment]
Hi,

I believe this issue is due to the fact you are asking for a taxonomic profile (with `--taxonomic-profile-krona`) but simultaneously specifying `--no-assign-taxonomy`. So a taxonomy profile without taxonomy. This should be a disallowed combination of options - will adjust the code to enforce this. I ran your archive through with
```
singlem renew --input-archive-otu-table arcivefile.zip -p a.profile
```
which ran to completion. Imagine that is it - feel free to comment further if there's more to the story.
Thanks.
