### ISSUE TITLE
suitability for co-abundance group detection

### ISSUE THREAD

**Issue by clb21565** [wwood/singlem#132]
Hello there! 

I was hoping to dereplicate a set of de novo generated OTUs from singlem and then use them as queries against a set of large, longitudinally sampled metagenomes. 

My thought was to use the relative abundance of the OTUs to identify OTU-level co-abundance groups. One concern is whether the short length of the OTUs will be problematic/add too much noise. Have you tried this/would you have any advice to share on this front?

**Comment by wwood** [comment]
Hi,

From memory, I tried that half-heartedly a long time ago. The nice thing is that you have a natural control - the OTUs from one species have different markers, and those markers should correlate.

However, I'm curious as to what your purpose is. Why not just genome recovery?

**Comment by clb21565** [comment]
we are generating MAGs too, but the data are very large and complex (deeply sequenced wastewater) and there is a substantial loss of information upon assembly. Also, bc it's wastewater, we get very poor classification rates using kraken2 (average of 30% using gtdb!) and so I'm hesitant to rely on the short read taxonomies. 

It's not a full idea yet though, definitely curious for your perspective

**Comment by wwood** [comment]
Ah right, OK.

Maybe something to try would be `singlem pipe -p` instead of kraken to get taxonomic profiles. Once you have MAGs, you can also add them to the singlem reference data with the new `singlem supplement` mode, and then rerun pipe (or renew if you save the archives).

HTH.
