### ISSUE TITLE
Relative abundances from taxonomic profiles

### ISSUE THREAD

**Issue by agatadziegiel** [wwood/singlem#138]
Hello,
Thanks so much for creating this tool and for the comprehensive installation and usage instructions!
I have a question regarding calculating relative abundances from the taxonomic profile outputs. How can this be done?
I have used the otu table to create a Krona plot, but I am specifically interested in some low abundance species that are not well represented there. Any suggestions would be highly appreciated!
Thank you.

**Comment by wwood** [comment]
Hi,

Thanks for the encouragement.

I'm a little confused about your question. Do you mean a taxonomic profile or an OTU table?

If you mean taxonomic profile, you can lessen the default threshold of 0.35X coverage by changing `--min-taxon-coverage`. Of course this comes at the potential cost of false positive identification of microbes.

HTH.

**Comment by agatadziegiel** [comment]
Hi,

Apologies if my question was unclear.
I have obtained both the taxonomic profile and OTU table with singlem pipe.
The main question is how to calculate the relative abundance from the taxonomic profile and/or the OTU table.

Thanks

**Comment by wwood** [comment]
Hi,

The relative abundance is shown in the taxonomic profile, no?

**Comment by agatadziegiel** [comment]
Hi,

The taxonomic profile contains the coverage; from the documentation, this indicates an "approximation of the total read coverage of all genomes from this taxon. However, note that this coverage does not include the coverage of sub-taxons. For instance, the coverage of a species is not included in the coverage shown for its genus". It's just a bit unclear to me as to how this translates to relative abundance, can you clarify please?

Thank you.

**Comment by wwood** [comment]
Ah, I see.

You make a good point - the data is all there, it is just that it isn't in the easiest form to digest. I'll try to add a new output from `summarise` which gives a site by species table - that's what you are after right?

You can manually figure it out by taking the coverage assigned to your taxon of interest (and all taxons underneath it in the tree if needed), and then divide by the total coverage assigned to all taxa - that will be your relabund.

**Comment by agatadziegiel** [comment]
Hi,

Thank you for the update!
I ran the new version on my samples and it did exactly what I needed.

Thanks again!

**Comment by wwood** [comment]
Great, thanks for the good idea and letting me know.
