### ISSUE TITLE
Clustering error

### ISSUE THREAD

**Issue by LanSabb** [wwood/singlem#140]
Hi @wwood 

I am currently using SingleM to cluster OTU tables using the following command  :

singlem summarise --input-otu-tables Sample_OTU.tsv --cluster  --clustered-output-otu-table Cluster_OTU.tsv

However, an error occurred as shown below. Do you have any idea how to resolve this issue?

09/21/2023 11:47:26 AM INFO: SingleM v1.0.0beta7
09/21/2023 11:47:26 AM INFO: Clustering OTUs with clustering identity 0.950000..
[2023-09-21T02:47:26Z INFO  bird_tool_utils::clap_utils] Smafa version 0.7.1
[2023-09-21T02:47:26Z INFO  smafa::cluster] Clustering ..
Error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
Traceback (most recent call last):
  File "/home/softwares/singlem/bin/singlem", line 795, in <module>
    o2.otu_table_objects = [list(Clusterer().each_cluster(otus, args.cluster_id))]
  File "/home/softwares/singlem/bin/../singlem/clusterer.py", line 86, in each_cluster
    centre = sequence_to_indexes[centroid_sequence][0]
KeyError: 'GGAGCATTCATTGAGTTGGCCGGAGGANNNNNNATAGTTGGACTCGTTCATATCTCGGAA'

Thanks!

**Comment by wwood** [comment]
Hi,

That seems like it might be a bug - would it be possible to send me the input OTU table somehow e.g. via email?
Thanks.

**Comment by wwood** [comment]
Thanks, indeed it was a bug, should be fixed now.

**Comment by LanSabb** [comment]
Thanks a lot !!
