### ISSUE TITLE
singlem data error

### ISSUE THREAD

**Issue by rzhan186** [wwood/singlem#144]
Dear singlem devlopers, 

I came across an issue trying to run singlem data using the docker container.
I ran the following command
```
apptainer run -C -B /project -W $PROJECT/software singlem-0.14.0.sif \
singlem data --output-directory /singleM/dbs

```
Received the following error: 

```
usage: singlem [-h]
               {data,pipe,appraise,seqs,makedb,query,summarise,read_fraction,renew,create,get_tree,regenerate,metapackage,chainsaw,condense,trim_package_hmms,supplement}
               ...
singlem: error: argument subparser_name: invalid choice: 'singlem' (choose from 'data', 'pipe', 'appraise', 'seqs', 'makedb', 'query', 'summarise', 'read_fraction', 'renew', 'create', 'get_tree', 'regenerate', 'metapackage', 'chainsaw', 'condense', 'trim_package_hmms', 'supplement')
```

Could you help with this? Thanks!

**Comment by wwood** [comment]
Hi,

The issue is that you have an extra `singlem` in your command. Try

```
apptainer run -C -B /project -W $PROJECT/software singlem-0.14.0.sif \
data -h
```

The other thing is, the SingleM database is already included in the docker container, there is no need to use `data` to download it again.

HTH, ben

**Comment by rzhan186** [comment]
Hi Ben, 

Thanks so much, that solved the problem! It's good to know about the pre-build database! Sorry for the dumb question ...

**Comment by wwood** [comment]
All good - I have tried to make the documentation clearer in response, and hope to add an Apptainer installation section soon.
