### ISSUE TITLE
singlem supplement KeyError:  's__spire_mag_01111928'

### ISSUE THREAD

**Issue by ellyyuyang** [wwood/singlem#158]
Hi Ben,

I thought this might be a better place to ask. I was trying to add 19+ MAGs into the metapackage (already HQ&MQ, so no need of quality filtering) using singlem supplement. But I ran into an error when running singlem supplement: **KeyError: 's__spire_mag_01111928'** after the step that _reads species-level taxon lengths from old metapackage_. The overall log file looks like:  

> 02/07/2024 04:09:53 PM INFO: SingleM v0.16.0
02/07/2024 04:09:53 PM INFO: Skipping quality filtering of new genomes
02/07/2024 04:09:53 PM INFO: Dereplicating new genomes using Galah ..
02/07/2024 04:09:53 PM INFO: Running galah to dereplicate 19253 genomes ..
02/07/2024 04:14:53 PM INFO: After dereplication, 5420 genomes remain
02/07/2024 04:14:53 PM INFO: Generating faa and transcript fna files for the new genomes ..
02/07/2024 04:15:10 PM INFO: Running prodigal on 5420 new genomes ..
xx/envs/singlem_v0.16.0/lib/python3.8/site-packages/singlem/supplement.py:704: TqdmWarning: Iterable length 5420 > 1000 but `chunksize` is not set. This may seriously degrade multiprocess performance. Set `chunksize=1` or more.
  transcripts_and_proteins = process_map(run_prodigal_on_one_genome, param_sets, max_workers=threads)
100%|██████████| 5420/5420 [21:33<00:00,  4.19it/s]
02/07/2024 04:36:44 PM INFO: Prodigal finished. Found 5 with translation table 4, 5415 with translation table 11
02/07/2024 04:36:46 PM INFO: Loaded 59 SingleM packages
02/07/2024 04:36:46 PM INFO: Generating taxonomy for new genomes ..
02/07/2024 04:36:46 PM INFO: Reading old taxonomies for checking concordance with new taxonomy strings ..
02/07/2024 04:37:52 PM INFO: Using pre-existing GTDBtk output directory: /projects/microflora_danica/shallow_mags/analysis/binning/gtdb_tax
02/07/2024 04:37:52 PM INFO: Reading taxonomy from xx/gtdb_tk/gtdbtk.bac120.summary.tsv
02/07/2024 04:37:52 PM INFO: Reading taxonomy from xx/gtdb_tk/gtdbtk.ar53.summary.tsv
02/07/2024 04:37:52 PM INFO: Writing new genome taxonomies to output_tax_file.tsv
02/07/2024 04:37:52 PM WARNING: There were 13833 genomes in the GTDBtk output that were not found in the list of genomes to be included. Ignoring these.
02/07/2024 04:37:52 PM INFO: Creating taxonomy file for new genomes
02/07/2024 04:37:52 PM INFO: Removed 804 genomes from new genomes list because they already had a species-level taxonomic assignment
02/07/2024 04:37:52 PM INFO: Number of new genomes to add to metapackage: 4616
02/07/2024 04:37:53 PM INFO: Generating new SingleM packages and metapackage ..
02/07/2024 04:37:53 PM INFO: Recalculating genome sizes for each species and higher level taxon ..
02/07/2024 04:37:56 PM INFO: Read 167824 species-level taxon lengths from old metapackage
Traceback (most recent call last):
  File "xxx/envs/singlem_v0.16.0/bin/singlem", line 1268, in <module>
    Supplementor().supplement(
  File "xxx/envs/singlem_v0.16.0/lib/python3.8/site-packages/singlem/supplement.py", line 855, in supplement
    new_metapackage = generate_new_metapackage(threads, working_directory, old_metapackage,
  File "xxx/envs/singlem_v0.16.0/lib/python3.8/site-packages/singlem/supplement.py", line 487, in generate_new_metapackage
    new_genome_sizes = recalculate_genome_sizes(
  File "xxx/envs/singlem_v0.16.0/lib/python3.8/site-packages/singlem/supplement.py", line 613, in recalculate_genome_sizes
    gc = gc.with_columns(pl.lit([species_to_full[s] for s in gc['species']]).alias('gtdb_taxonomy'))
  File "xxx/envs/singlem_v0.16.0/lib/python3.8/site-packages/singlem/supplement.py", line 613, in <listcomp>
    gc = gc.with_columns(pl.lit([species_to_full[s] for s in gc['species']]).alias('gtdb_taxonomy'))
KeyError: 's__spire_mag_01111928'

The code I ran was:
`singlem supplement  
--new-genome-fasta-files-list genome-fasta-files.list 
--input-metapackage xx/singlem0.16.0/uhgg_smag_spire_oceans_gems.smpkg 
--output-metapackage xx/singlem0.16.0/uhgg_smag_spire_oceans_gems_mfd_shortreadMAGs.smpkg 
--threads 60 --pplacer-threads  60 
--working-directory xx/singlem0.16.0/uhgg_smag_spire_oceans_gems_mfd_shortreadMAGs  
--gtdbtk-output-directory gtdb_output/ 
 --output-taxonomies output_tax_file.tsv 
--no-quality-filter 
--checkm2-quality-file xx/checkm2/quality_report.tsv 
--checkm2-min-completeness 50
--checkm2-max-contamination 10 
--dereplicate-with-galah`

Thanks!
Yu

**Comment by wwood** [comment]
Hi,

I think this was caused by an issue where one of the previously added genomes (the one with the key error) is quite poor quality, to the point where no markers from it are used in the updated singlem package, which cuases issues when you try to re-supplement" the smpkg. Let me know how you go.

**Comment by wwood** [comment]
To be clear, you shouldn't encounter this issue in the main branch any more, the new code accounts for this situation.

I think alternatively you can just use --no-taxon-genome-lengths with v0.16.0 (I think).
