### ISSUE TITLE
Inconsistent numbers in appraise

### ISSUE THREAD

**Issue by adityabandla** [wwood/singlem#165]
Hi Ben,

I used appraise to assess the number of MAGs recovered from my metagenomes. For certain metagenomes, the number binned >> than the actual number of MAGs recovered from that particular domain. So I'm a bit confused about how to assess these numbers. Are these averaged across different markers when using the default metapackage?

Regards, Adi

**Comment by adityabandla** [comment]
Thanks, Ben! If I got this correct, num_binned = sum of coverages of binned populations detected in the metagenome, and num_not_found = sum of coverages of populations in the metagenomes not in the genomes?

**Comment by wwood** [comment]
Right. Could probably be explained a bit better, so let's leave this open until something is done about that.

**Comment by adityabandla** [comment]
Thanks, Ben, sure! If num_binned can be renamed as cov_binned, for example, it's a lot more intuitive

**Comment by wwood** [comment]
@AroneyS what do you think about renaming? To say binned_coverage and unbinned coverage?
