### ISSUE TITLE
singlem supplement command failed to finish successfully 

### ISSUE THREAD

**Issue by VadimDu** [wwood/singlem#168]
Dear @wwood, devs/users,

I am trying to supplement the default metapackage with additional genome/genomes. I run the following command:

`singlem supplement --new-genome-fasta-files BL2bin.13_genomic.fna --new-taxonomies BL2bin.13_gtdb_taxonomy.tsv --input-metapackage S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb/payload_directory/ --output-metapackage metapackage_20231006_plus_BL2bin.13 --no-dereplication --no-taxon-genome-lengths --no-quality-filter --working-directory tmp_dir/`

I encountered the following error (see traceback):
```
  File "/mnt/data_1/singlem/bin/singlem", line 1279, in <module>
    Supplementor().supplement(
  File "/mnt/data_1/singlem/bin/../singlem/supplement.py", line 891, in supplement
    new_metapackage = generate_new_metapackage(threads, working_directory, old_metapackage,
  File "/mnt/data_1/singlem/bin/../singlem/supplement.py", line 544, in generate_new_metapackage
    SequenceDatabase().create_from_otu_table(
  File "/mnt/data_1/singlem/bin/../singlem/sequence_database.py", line 500, in create_from_otu_table
    c.execute("CREATE INDEX otu_sample_name on otus (sample_name)")
sqlite3.OperationalError: database or disk is full
```
Needles to say I have over 1TB of free space in the mounted disk, and running SingleM on a server. If needed I can attach the full log of the command, but I can add that it already created the following dirs: prodigal_output, concatenated_alignment_hmms.hmm, hmmsearch_output, matched_transcripts.fna, new_metapackage.sdb.
In new_metapackage.sdb dir there is a CONTENTS.json and otus.sqlite3 files.

Any help will be much appreciated,
Best regards,
VadimD

**Comment by wwood** [comment]
Hi,

My suspicion here is that temporary files outside the working directory are being created. What happens when you set the TMPDIR to your storage?

SingleM should be setting the TMPDIR itself to somewhere inside the working directory if specified, will fix.

**Comment by VadimDu** [comment]
Hi @wwood,

Thank you for the very fast response.

I couldn't find a specific flag for setting a temp directory, but I set '--working-directory' to the local storage dir (`./tmp_dir/`), thus nothing should be written outside (e.g. to the system tmp dir).

In the description of this flag written: "working directory [default: use a temporary directory]", so I assumed that If I "manually" set one, it shouldn't write to temp dir.

**Comment by wwood** [comment]
Right, understand your reasoning.

But you also need to set the TMPDIR environment variable, which python's tempfile library respects. I'll fix it so this isn't needed in future, likely by the next versiin 0.17.0, but for now you'll have to set it yourself.

**Comment by wwood** [comment]
Fixed in the main branch now, so if you want you can run it from there. Thanks for the report.
