### ISSUE TITLE
`singlem summarise --input-archive-otu-table-list` incorrectly triggers an error

### ISSUE THREAD

**Issue by luispedro** [wwood/singlem#171]
```bash
singlem summarise --input-archive-otu-table-list ...
```

triggers an error:

```
Exception: Summary requires input OTU tables, archive OTU tables, or taxonomic profiles
```

I think the check is incorrect (as having `input_archive_otu_table_list` should be enough):

https://github.com/wwood/singlem/blob/fbf9f1494829cd8718141a0ff233aa1d349e2b01/bin/singlem#L771

**Comment by wwood** [comment]
Nah the check was missing one. Death by argparse...

thanks.
