### ISSUE TITLE
ETA on updated metapackage for GTDB Release09-R220

### ISSUE THREAD

**Issue by julianzaugg** [wwood/singlem#180]
Hey Ben,

Just checking what the ETA is for an updated metapackage for GTDB Release09-R220?

Thanks!

**Comment by wwood** [comment]
Hey,

I have one already and is in need of a beta tester.. interested?

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Julian Zaugg ***@***.***>
Sent: Thursday, May 16, 2024 4:17:56 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] ETA on updated metapackage for GTDB Release09-R220 (Issue #180)


Hey Ben,

Just checking what the ETA is for an updated metapackage for GTDB Release09-R220?

Thanks!

―

**Comment by julianzaugg** [comment]
Yes, happy to test!

**Comment by wwood** [comment]
oh, you'll need the newest smafa, which is currently not on bioconda because bioconda CI is fail at the moment - https://github.com/bioconda/bioconda-recipes/pull/47843

In the meantime you'll need to install using `cargo intsall smafa` or similar

**Comment by julianzaugg** [comment]
Good timing, I was just setting up. Is the latest smafa required for using the R220 database (I was planning on just using with ver. `0.16.0`), or do I need to use it with ver. `0.17.0`?

**Comment by wwood** [comment]
Yes, required for 0.16 too. Db format change

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by wwood** [comment]
Hey I've found a bug in the r220 package - remaking it now - will send an udpated version.

**Comment by wwood** [comment]
A pretty bad bug - don't trust results from the previous r220 metapackage I sent.

**Comment by wwood** [comment]
Closing now as 0.18.0 uses r220 by default
