### ISSUE TITLE
raise Exception("Bad SingleM metapackage version: %s" % str(v))

### ISSUE THREAD

**Issue by kellynntan** [wwood/singlem#182]
Hi,

I recently installed singlem and the metapackage. I tried running pipe using the S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb metapackage and was given the following error:

  raise ZenodoBackpackMalformedException(
zenodo_backpack.ZenodoBackpackMalformedException: Version in CONTENTS.json: 4.3.0 does not match version provided: 3.2.1

Then I tried to specify --metapackage but was given the following error: 

  File "/singlem/bin/../singlem/metapackage.py", line 111, in acquire
    raise Exception("Bad SingleM metapackage version: %s" % str(v))
Exception: Bad SingleM metapackage version: 5

Would you be able to advise if it's an issue on my part and how would I be able to fix it?
Thank you.

**Comment by wwood** [comment]
Hi,

I think this would probably be solved by updating to the newest version of SingleM 0.18.0? It is fresh off the press, those errors are to prevent old versions of SingleM trying to use newer database formats.

**Comment by kellynntan** [comment]
Whoops that totally worked. Thank you so much!
