### ISSUE TITLE
Creating new metapackage with singleM supplement

### ISSUE THREAD

**Issue by aprabhu90** [wwood/singlem#183]
Hi Ben,

I wanted to create a new singleM metapackage with custom genomes and I'm currently having issues with creating one. 
I'm using the `singleM_0.18.0` and the metapackage is `S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb`

I've done this before for the R214 metapackage, however, this time when I try to create one, I get the following constant running code. The program runs for a long time but does not create the marker hmm files for the new metapackage : 
`Traceback (most recent call last):
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/bin/singlem", line 1368, in <module>
    Supplementor().supplement(
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/site-packages/singlem/supplement.py", line 945, in supplement
    new_metapackage = generate_new_metapackage(threads, working_directory, old_metapackage,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/site-packages/singlem/supplement.py", line 500, in generate_new_metapackage
    matched_transcripts_fna = gather_hmmsearch_results(num_threads, working_directory, old_metapackage,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/site-packages/singlem/supplement.py", line 446, in gather_hmmsearch_results
    map_result = pool.starmap(
                 ^^^^^^^^^^^^^
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/centos7/sw/miniconda3/envs/singlem_0.18.0/lib/python3.12/threading.py", line 355, in wait
    waiter.acquire()
KeyboardInterrupt`

The new taxonomy file looks like this 
`/srv/scratch/apoorva/for_arb/singlem/test/1445893_12EF_03.semibin_refined.165.fasta     d__Archaea;p__Asgardarchaeota;c__Heimdallarchaeia;o__Heimdallarchaeales;f__Kariarchaeaceae;g__Kariarchaeum;s__001
/srv/scratch/apoorva/for_arb/singlem/test/1445891_12EF_01.semibin_refined.167.fasta     d__Archaea;p__Asgardarchaeota;c__Heimdallarchaeia;o__Heimdallarchaeales;f__Kariarchaeaceae;g__Kariarchaeum;s__001
/srv/scratch/apoorva/for_arb/singlem/test/1445901_13EF_02.metabat2_refined.027.fasta    d__Archaea;p__Asgardarchaeota;c__Heimdallarchaeia;o__Heimdallarchaeales;f__Kariarchaeaceae;g__Kariarchaeum;s__001
/srv/scratch/apoorva/for_arb/singlem/test/1445888_12SH_01.concoct.045.fasta     d__Archaea;p__Asgardarchaeota;c__Heimdallarchaeia;o__Heimdallarchaeales;f__Kariarchaeaceae;g__Kariarchaeum;s__001
/srv/scratch/apoorva/for_arb/singlem/test/1445898_13SH_02.vamb.093.fasta        d__Archaea;p__Asgardarchaeota;c__Heimdallarchaeia;o__Heimdallarchaeales;f__Kariarchaeaceae;g__Kariarchaeum;s__001`

and this is my command 
`singlem supplement --new-genome-fasta-files *.fasta --threads 30 --new-fully-defined-taxonomies newnames5.txt --skip-taxonomy-check  --no-quality-filter --no-dereplication --working-directory /singlem/test/  --input-metapackage db/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb --output-metapackage test.smpkg --ignore-taxonomy-database-incompatibility --no-taxon-genome-lengths`

Could you please tell me if you think anything is incorrect? Thank you!

**Comment by aprabhu90** [comment]
Ok, I ended up re-downloading singleM and metapackages and it all seems to be working now. All good!

**Comment by wwood** [comment]
Hi @aprabhu90 sorry for the slow response here. I would suggest not putting >1 genome into a metapackage. Doing so breaks some assumptions it makes.

Also curious why you are using `--ignore-taxonomy-database-incompatibility` ? This is not needed if you are building off the default metapackage.

**Comment by aprabhu90** [comment]
Hi Ben, 
Yep - all good, I was struggling earlier with one of the beta versions before I realised there was v.0.18.0 .  Also yes I didn't need the `--ignore-taxonomy-database-incompatibility` flag, at the time I was just checking with 5 genomes to see what was going wrong with creating the metapackage. 

Also could I ask what does "suggest not putting >1 genome into a metapackage." mean please? From the paper I created a new one with newly named taxa, which were hundreds of MAGs - it worked pretty good, I compared it before and after the new metapackage to check.

**Comment by wwood** [comment]
Sorry I mean >1 genome from the same species, as your taxonomy file seems to imply. Glad it worked out for you, closing.
