### ISSUE TITLE
singlem: error: unrecognized arguments: --otu_table

### ISSUE THREAD

**Issue by zehanna** [wwood/singlem#201]
Hi, thank you very much for creating this amazing program.
I want to run the singleM appraise pipeline, however I'm having some issues with the `singlem pipe` command.
I have tried it both with the conda installation (v0.18.3) and with the singularity image (downloaded today).

When I try to run singleM on the genome files:

```
singlem pipe --genome-fasta-files *.fa --otu_table \
    genomes.otu_table.csv
```

I get the error:
```
usage: singlem [-h] {data,pipe,appraise,seqs,makedb,query,summarise,microbial_fraction,renew,create,get_tree,regenerate,metapackage,chainsaw,condense,trim_package_hmms,supplement} ...
singlem: error: unrecognized arguments: --otu_table  genomes.otu_table.csv
```

The same when I want to run it on the reads:
```
singlem pipe -1 sample1_PE1.fq.gz -2 sample1_PE2.fq.gz --otu_table sample1_otu_table.csv
usage: singlem [-h] {data,pipe,appraise,seqs,makedb,query,summarise,microbial_fraction,renew,create,get_tree,regenerate,metapackage,chainsaw,condense,trim_package_hmms,supplement} ...
singlem: error: unrecognized arguments: --otu_table /cluster/project/umbiol/projects/Cadagno_lake_sediment_2024/SingleM/appraise/sample1_otu_table.tsv
```

I followed the instructions here: https://wwood.github.io/singlem/tools/appraise
And I can't find anything that I do differently in the command.

Can you think of a reason why I get this error?

Thanks a lot in advance for your help.

**Comment by wwood** [comment]
Hi,

Thanks for the kind words.

It should be --otu-table not --otu_table.

It's an error in the docs, thanks for pointing it out.
Ben

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: zehanna ***@***.***>
Sent: Friday, December 6, 2024 9:37:06 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] singlem: error: unrecognized arguments: --otu_table (Issue #201)


Hi, thank you very much for creating this amazing program.
I want to run the singleM appraise pipeline, however I'm having some issues with the singlem pipe command.
I have tried it both with the conda installation (v0.18.3) and with the singularity image (downloaded today).

When I try to run singleM on the genome files:

singlem pipe --genome-fasta-files *.fa --otu_table \
    genomes.otu_table.csv


I get the error:

usage: singlem [-h] {data,pipe,appraise,seqs,makedb,query,summarise,microbial_fraction,renew,create,get_tree,regenerate,metapackage,chainsaw,condense,trim_package_hmms,supplement} ...
singlem: error: unrecognized arguments: --otu_table  genomes.otu_table.csv


The same when I want to run it on the reads:

singlem pipe -1 sample1_PE1.fq.gz -2 sample1_PE2.fq.gz --otu_table sample1_otu_table.csv
usage: singlem [-h] {data,pipe,appraise,seqs,makedb,query,summarise,microbial_fraction,renew,create,get_tree,regenerate,metapackage,chainsaw,condense,trim_package_hmms,supplement} ...
singlem: error: unrecognized arguments: --otu_table /cluster/project/umbiol/projects/Cadagno_lake_sediment_2024/SingleM/appraise/sample1_otu_table.tsv


I followed the instructions here: https://wwood.github.io/singlem/tools/appraise
And I can't find anything that I do differently in the command.

Can you think of a reason why I get this error?

Thanks a lot in advance for your help.

―

**Comment by zehanna** [comment]
Amazing, it's working now, thank you!

I just have one other question: when I run `singlem pipe` on the assembly file, which flag should I use? The same as for the genomes? E.g.

`singlem pipe --genome-fasta-files scaffolds.fasta --otu-table assembly.otu_table.csv 
`

Or another one? I couldn't find another flag specific for assembly files.

**Comment by wwood** [comment]
`--genome-fasta-files` is probably best for now. It isn't the most efficient, and can take some TMPDIR space so we are working on an alternate method, but it'll do for now.

**Comment by zehanna** [comment]
Great, thank you very much for your answers!
