### ISSUE TITLE
question on handling multiple samples

### ISSUE THREAD

**Issue by AdvancedBiomeasurementsResearchGroup** [wwood/singlem#22]
Hi,

I am using singleM and had a question regarding how to set up analysis of multiple samples. Basically, should multiple samples by analyzed together by specifying multiple sequence files or is it better to merge the otu tables after running each sample separately? 

More specifically, when using clustering of the OTU sequences, how are the number of hits updated for different samples when they were analyzed together, or hits combined on a per-sample basis (I guess that should lead to zeros in some cases but when I run such analyzed the min number of hits is 1).

Thank you for developing this tool, seems very useful.

Thanks,

Dieter

**Comment by wwood** [comment]
Hi Dieter,

> I am using singleM and had a question regarding how to set up analysis of multiple samples. Basically, should multiple samples by analyzed together by specifying multiple sequence files or is it better to merge the otu tables after running each sample separately?

Either way is fine - There isn't any difference between running `singlem pipe` with multiple input files, or running them individually and then merging them with `singlem summarise`.

> More specifically, when using clustering of the OTU sequences, how are the number of hits updated for different samples when they were analyzed together, or hits combined on a per-sample basis (I guess that should lead to zeros in some cases but when I run such analyzed the min number of hits is 1).

The clustering operates on all OTUs in the input file(s) together. There's no 'zero count OTUs' where a cluster contains no OTUs from a sample, because these are omitted.

> Thank you for developing this tool, seems very useful.

Thanks for using SingleM and seeing some potential.
ben

**Comment by AdvancedBiomeasurementsResearchGroup** [comment]
Dear Ben,

Thank you very much for the clarification.

Btw, I also noticed that the script sometimes throws a 'too many files open' error (I am running on osx). I worked around that by increasing ulimit but I was curious as to whether you know the cause of this issue.

Dieter

**Comment by wwood** [comment]
OK, glad that made sense.

The ulimit issue is a reason to run samples with `singlem pipe` individually, I suppose. I came across that issue too - see #20. Let me know if there is anything else.
ben

**Comment by wwood** [comment]
Hi again Dieter,
I believe that the too many open files issue #20 has been resolved in the master branch. The next released version on PyPI (likely 0.9.0) should include this fix also.
