### ISSUE TITLE
submission to Conda?

### ISSUE THREAD

**Issue by jacodela** [wwood/singlem#23]
The `SingleM` package looks like a very useful tool for microbial genomics. As far as I can tell, it's not available from Conda, as are other tools from the M-Tools suite. Are there any plans to make it available via Conda?

**Comment by wwood** [comment]
Hi. Apologies for the slow response. 

I would like to and I don't see any reason why it couldn't be, particularly as the Guix recipes define the dependencies required. I did spend a little time trying to get GraftM to work correctly but that failed, presumably out of my ignorance (actually fastalite needed to be packaged, for a start). I would appreciate some help if you or anyone could spare it .. Thanks.

**Comment by wwood** [comment]
SIngleM is now on conda.
