### ISSUE TITLE
Suggestion for paired Reads?

### ISSUE THREAD

**Issue by michoug** [wwood/singlem#25]
Hi,
I wondered if you had a suggestion on how to deal with paired reads using the software, as I didn't really saw anything in the readme regarding this issue
Best
Greg

**Comment by wwood** [comment]
Hi Greg,

You ask a good question. I have not come up with a proper solution to this yet, which might be to detect when both reads in a pair match to the same gene, and in that case only count it once.

Personally, I either just use the forward reads, or if I need more depth in the table, collapse the forward and reverse into a single sample with `singlem summarise --collapse_coupled`.

ben

**Comment by wwood** [comment]
Fixed in release v0.12.0
