### ISSUE TITLE
Minimal system requirements (namely RAM)?

### ISSUE THREAD

**Issue by vinisalazar** [wwood/singlem#29]
Are there any recommended minimal system requirements to run this program? I want to install it on my machine (8gb RAM, 2.6GHz i5) but am afraid it will crash. Feedback would be appreciated.

**Comment by wwood** [comment]
Hi,

I've not rigorously tested this, but I just ran a soil sample through the default 'pipe' pipeline using <2.5GB of RAM. The most RAM intensive step is probably the taxonomic assignment step, and for that you can probably use `--assignment_method diamond` to reduce that further. It will take more RAM if using more threads, I suspect, but as a default of 1 you should be good.
Good luck. ben

**Comment by vinisalazar** [comment]
That's great to know. Thank you for the reply.
