### ISSUE TITLE
Paired end sequence data has redundant IDs

### ISSUE THREAD

**Issue by ParkvilleData** [wwood/singlem#30]
Hi,

When using paired end reads, one after the other on the sequences parameter I occasionally get redundant ID errors. This only happens on about 20% of the samples. I changed the names of the headers and tried the samples again but they still result in  the same error. 

Is there any way to resolve this issue? Possibly using collapse_coupled? and would this happen before singlem pipe?

Thanks,
Bobbie

**Comment by wwood** [comment]
Hi,
Do you mean when if you run `single pipe --sequences read1.fq read2.fq` ? Really the way to resolve this is to properly handle paired end data, as in #25 but in the meantime can you just run them as separate singlem pipe runs?
ta

**Comment by ParkvilleData** [comment]
Hi, yes, that's exactly how I ran it. 

So as in #25, that would be to collapse the reads? I know it is possible to merge otu tables but I would prefer to merge the reads as is done in MG-RAST. Does the collapse_coupled merge with an overlap (as in flash) or concatenate? 
Thanks for the quick response!

**Comment by wwood** [comment]
No problem - `collapse_coupled` if for concatenating otu tables. There's no realigning of the reads or anything. If there is a forward and a reverse detected, then that will count as 2 reads. It isn't ideal I understand, but at least you'll end up with a single OTU table. Alternatively you can just ignore the reverse reads and only use the forward (again, not ideal).

I just improved the collapse_coupled documentation in bf183c3 on the dev branch - let me know if you have any suggestions.

Thanks.

**Comment by wwood** [comment]
Fixed in release v0.12.0 - you can now specify `--forward` and `--reverse`
