### ISSUE TITLE
paired end option doesn't seem to work

### ISSUE THREAD

**Issue by SamLambrechtsUGent** [wwood/singlem#33]
When I specify singlem pipe like so:

`singlem pipe --forward ERR_PA_4_2018_1.fastq --reverse ERR_PA_4_2018_2.fastq --otu_table PA_4_shtgn_singleM_otu_table.csv --threads 10`

I get:

```
05/03/2019 05:21:22 PM INFO: Using as input 1 different sequence files e.g. ERR_PA_4_2018_1.fastq
05/03/2019 05:21:22 PM INFO: Searching with 14 SingleM package(s)
05/03/2019 05:21:22 PM INFO: Searching for reads matching 28 different protein HMM(s)
05/03/2019 05:39:43 PM INFO: Finished search phase
05/03/2019 05:39:43 PM INFO: Running separate alignments in GraftM..
05/03/2019 05:40:11 PM INFO: Finished extracting aligned sequences
05/03/2019 05:40:11 PM INFO: Running taxonomic assignment with GraftM..
05/03/2019 05:50:32 PM INFO: Finished running taxonomic assignment with GraftM
05/03/2019 05:50:33 PM INFO: Finished
```

The first sentence in that report and the output otu table tell me that only ERR_PA_4_2018_1.fastq was used, and not the second one. Any idea why? I'm using raw paired end files (no quality or adapter trimming performed), and I installed singlem using pip. When I run `singlem --version` I get `0.12.1`

**Comment by wwood** [comment]
Hi,
Not to worry. This is just an issue with the way things are reported on STDERR. In the background, they are being treated as paired-end. Do you have any other evidence to the contrary?

I'll leave this issue open as a reminder to fix the logging.

Thanks, ben

**Comment by SamLambrechtsUGent** [comment]
Hi Ben,

Thank you for your answer. I checked htop, and I can confirm that at least in one part of the pipeline (orfm if I recall correctly), the reverse `ERR_PA_4_2018_2.fastq` file was being used. So I have no evidence to the contrary and believe you're right. Thank you for clearing this out
