### ISSUE TITLE
Read assigned to Eukaryotes

### ISSUE THREAD

**Issue by pm-leung** [wwood/singlem#41]
Hi Ben,

I have got some minor issues about reads assigned to eukaryotes. I wonder if 14 universal single-copy ribosomal marker genes for prokaryotic community profiling are also applicable for eukaryotes, as the presence of which in eukaryotes hasn't been benchmarked (as far as I know). How well does SingleM capture the community structure for eukaryotes in a sample? If only a few of eukaryotic taxa can be captured, the relative abundance information can be skewed. Currently, I am just filtering out eukaryotic and unassigned reads from the analysis for a prokaryotic community only.  Do you have any suggestions for handling and interpreting non-prokaryotic data?

Many thanks,
Bob

**Comment by wwood** [comment]
Hi,

Yes I think you have the right idea - classifying OTUs as euks is for making sure they don't contaminate bacterial/archaeal profiles. The tool isn't (at least currently) meant as a euk profiler, in part because introns might interfere with the ORF calling, which happens on a per-read basis.

**Comment by rachaellappan** [comment]
Hi Ben,

As an extension to this, does SingleM provide a reasonable estimate of overall eukaryotic relative abundance? Or are there potentially large numbers of eukaryotes not captured by ribosomal protein homology?

**Comment by wwood** [comment]
Hi,

SingleM isn't meant to assess the eukaryotic community, in particular because (1) it isn't clear the genes used are single copy in Eukarya, and (2) the genomic DNA sequences may include introns. I have found it qualitatively useful on occasion though.

**Comment by Ge0rges** [comment]
Hi Ben, I also wanted to follow up on this and ask what tool you use to assess eukaryotic contamination (human)/fraction in your microbial samples?

**Comment by wwood** [comment]
Hi.

There is some discussion here - https://github.com/wwood/singlem/issues/167 - but the documentation could definitely be improved. It isn't based on finding eukaryotic OTUs, but rather subtracting microbial read count (estimated via the SingleM taxonomy profile) from the total numbe of reads in the metagenome.

If you want to look at human read fraction though, I would probably suggest simple mapping to the human genome, as that is probably more direct. If you have further comments, please open a new issue.

**Comment by Ge0rges** [comment]
Got it. Human was an example here (that's exactly what I do), I'm just curious to hear from you what you typically use as the eukaryotic equivalent of singleM if anything. I've defaulted to Kraken2 but am not incredibly (subjectively) happy with its results.

**Comment by wwood** [comment]
Oh I see - yes that is hard, particularly for protists since there is so few genomes for the amount of diversity.
