### ISSUE TITLE
Differrence between 14 genes

### ISSUE THREAD

**Issue by jlli6t** [wwood/singlem#44]
Hi Ben,

After read through the document, I did't find information describing the difference between 14 genes. I was confused about how to read the result of 14 different genes.

Could you please provide more info about this? Thank you alot.

**Comment by wwood** [comment]
Hi,

This is a good question, but there's unfortunately not a straightforward answer. I treat singlem outputs similar to technical replicates. Each of these genes aims to give a community profile for the entire community.

Does that help? Do you have a specific question you want to ask of the data?

**Comment by jlli6t** [comment]
Hi Ben,
Yes, I am checking with binned genomes, results of 14 genes are inconsistent, I am a little confused which to look at.

**Comment by wwood** [comment]
Hmm, can you be a bit more specific?
________________________________

**Comment by jlli6t** [comment]
Sure Ben, Thank you. I used the appraise module to assess the unrecovered genomes, these 14 genes told me different species that haven't been recovered, for example, S1.2.ribosomal_protein_L3_rplC tells me that there is (are) Betaproteobacteriales unrecovered, while S1.4.ribosomal_protein_L6_rplF tells me that both Betaproteobacteriales and Methanosarcinales are unrecovered, S1.8.ribosomal_protein_S2_rpsB tells me Phycisphaerae hasn't been recovered, however, S1.9.ribosomal_protein_S5 tells me that Ignavibacterium was missed. Those genomes are also all reported with relatively high proportion of reads.

They do reported some genomes shared, like over half of the gene's result considering that Betaproteobacteriales was missed, which I think it's easy to agree. But others I am confused about them. Do you have suggestion?

**Comment by wwood** [comment]
I see, I wasn't clear you were using appraise. I'm still a bit confused about what you are asking though, would you be able to give the appraisal result somehow?

Thanks, ben
