### ISSUE TITLE
Clustering thresholds for different ribosomal proteins

### ISSUE THREAD

**Issue by adityabandla** [wwood/singlem#50]
Are there any recommended % identity thresholds for clustering ribosomal proteins into species-level groups? Olm et al https://msystems.asm.org/content/5/1/e00731-19.full seems to be the only one I could find, but not really sure if numbers for full-length sequences still remain valid for shorter sequences that singleM recovers

**Comment by wwood** [comment]
Hi Aditya,

You ask a good question. I've not evaluated if say a 95% ANI values translates well into a singlem OTU divergence. I would suspect that you'd be better off comparing genomes given there's more data to work with there, but I suppose you aren't in a position to do that given the form of your data. I will attempt to answer this in future as I imagine it will form part of the paper.

Hope that helps, though I suspect it won't.
ben

**Comment by adityabandla** [comment]
Hi Ben,

Circling back to this issue about the clustering threshold. I see that the threshold approximating species divergence is set at 96.67, was wondering how this was arrived at?

Cheers, Adi

**Comment by wwood** [comment]
Hi,

There is some details about this in the SingleM sandpiper preprint, in the supplementary.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
