### ISSUE TITLE
Assignment of chlorplast RPs

### ISSUE THREAD

**Issue by suskraem** [wwood/singlem#51]
Hello,

I was wondering how chloroplast RPs are assigned with singleM. I don't think there is a category for chlorplasts in the database singleM uses. Are they assigned to Eukarya or maybe to Cyanobacteria?

Thanks a lot!

**Comment by wwood** [comment]
Hi, thanks for your interest.

They are meant to be Eukarya.
ben

**Comment by suskraem** [comment]
Hello Ben,

thanks for your reply. What would be the taxonomic string for chloroplast RPs?

Thanks!

**Comment by wwood** [comment]
Hi,

In most cases they should be `Eukaryota; Plantae`, using either diamond or pplacer assignment methods. GraftM, which interprets the the pplacer results, does not require monophyly in the reference trees to assign taxonomy.

Let me know if that doesn't square with your observations.
ben
