### ISSUE TITLE
orator version fault with conda

### ISSUE THREAD

**Issue by zhanwen-cheng** [wwood/singlem#56]
Hi wwood, I was trying to install singlem with conda "conda install singlem". As it always showed "Solving environment: | failed with repodata from current_repodata.json, will retry with next repodata source"  and took long time with conda, I change conda to mamba, and install single with "mamba install singlem", it reported "Problem: package singlem-0.13.2-py_0 requires orator >=0.9.7, but none of the providers can be installed" as 
![image](https://user-images.githubusercontent.com/26667865/95594882-133f3a80-0a7e-11eb-983d-bd79a0708469.png)

Thus I installed orator with pip "pip install orator", and the packages was installed successfully.
![image](https://user-images.githubusercontent.com/26667865/95595186-78932b80-0a7e-11eb-9055-a4ba404728ec.png)

And I re-install singlem with "mamba install singlem", but it reported the same error.
![image](https://user-images.githubusercontent.com/26667865/95595646-fb1beb00-0a7e-11eb-9003-333876db751a.png)

Can you help me with that?

**Comment by wwood** [comment]
Hi,

Thanks for your interest. I tried it this morning and found it installed from conda without issue:

```
❯ conda create -p /tmp/singlem singlem -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /tmp/singlem

  added / updated specs:
    - singlem


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backpack-0.1               |        py36_1000          20 KB  conda-forge
    biom-format-2.1.8          |   py36hc1659b7_0        10.4 MB  conda-forge
(snip)
```

I wonder if you might have more success creating a new environment rather than installing into an existing one?

**Comment by zhanwen-cheng** [comment]
Hi, wwood, I install singlem in a specific path as you pointed and it succeeded!
Thanks!
