### ISSUE TITLE
"ktUpdateTaxonomy.sh" errors

### ISSUE THREAD

**Issue by LiZhihua1982** [wwood/singlem#92]
Hi Everyone,
When I use "ktUpdateTaxonomy.sh" it report errors "ERROR: Curl (http://curl.haxx.se) is required." How to solve?  Many thanks!

**Comment by wwood** [comment]
Hi,

That script is from KronaTools https://github.com/marbl/Krona so you are better off asking there I think. curl is a very common command line tool that shouldn't be hard to install.

Where did you encounter this error in SingleM?
Thanks, ben

**Comment by LiZhihua1982** [comment]
Thank you very much for your reply! Yes, I meet this problem in SingleM!

________________________________
发件人: Ben J Woodcroft ***@***.***>
发送时间: 2022年7月22日 5:15
收件人: wwood/singlem ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [wwood/singlem] "ktUpdateTaxonomy.sh" errors (Issue #92)


Hi,

That script is from KronaTools https://github.com/marbl/Krona so you are better off asking there I think. curl is a very common command line tool that shouldn't be hard to install.

Where did you encounter this error in SingleM?
Thanks, ben

―

**Comment by wwood** [comment]
Thanks for the response. When within SingleM was this an issue?

**Comment by LiZhihua1982** [comment]
Hi,
  when install SingleM "conda create -c bioconda --name singlem singlem" and  then "ktUpdateTaxonomy.sh". Thanks!

Zhihua

________________________________
发件人: Ben J Woodcroft ***@***.***>
发送时间: 2022年7月22日 5:15
收件人: wwood/singlem ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [wwood/singlem] "ktUpdateTaxonomy.sh" errors (Issue #92)


Hi,

That script is from KronaTools https://github.com/marbl/Krona so you are better off asking there I think. curl is a very common command line tool that shouldn't be hard to install.

Where did you encounter this error in SingleM?
Thanks, ben

―

**Comment by wwood** [comment]
OK. I think that is really an issue with bioconda, not singlem, but you can fix by installing curl first (perhaps through conda, and activating the env) and then conda installing singlem.

**Comment by LiZhihua1982** [comment]
Thank you for your suggestion! I can fix this probelm now, In the SingleM envrionment,  conda install krona, to reinstall krona. That is OK!

**Comment by wwood** [comment]
Glad its sorted.
