### ISSUE TITLE
SingleM result

### ISSUE THREAD

**Issue by LiZhihua1982** [wwood/singlem#93]
Hi,
   when "singlem pipe --forward GJ4_1.fq.gz --reverse GJ4_2.fq.gz  --otu_table GJ4_otu_table.csv --threads 20 --assignment_method diamond" . The results showed only GJ4_1  in the sample colume of GJ4_otu_table.csvas below. I do not know whether it is OK or just analysis the forward sequences G4_1 sample? 

S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCAGTAATTATCACCCCTGAAGGTGAAATGAAAGGCTCAGAAATCAGAGGCCCAGTT | 2
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCAGTGATCATATCTCCTGATGGAGTTTTGAAAGGCTCTGAAATAAGAGGACCAGTG | 21
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAATGGTAATTACGGATGAAGAGGGAGTACCCAAAGGCACGGACATAAAAGGTCCCGTA | 6
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCATGGTAATCACGGATGAAGACGGGATTCCAAAAGGCACGGACATAAAAGGTCCTATA | 40
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCATGGTAATCACGGATGAAGATGGGATTCCCAAAGGCACGGACATAAAAGGTCCTGTA | 10
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTATGGTAATCACGGACGAAGATGGTATTCCCAAAGGGACGGACATAAAAGGTCCTGTA | 4
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCTGTTATACTCTCGACAGATGGAGTGCTTAAGGGTTCTGAAATAAGAGGACCAATA | 14
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCAGTGATCATATCTCCTGATGGAGTTTTGAAAGGCTCTGAAATAAGGGGACCAGTG | 2
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTATGGTAATTACGGATGAAGAGGGAGTACCCAAAGGCACGGACATAAAATGTCCCGTA | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCTGTAATAGTATCCCCTGAGGGTGTACTAAAAGGTTCTGAAATAAGGGGACCAATT | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCATGGTGCTCGTCAACGAGCGCGACGAGCCGAAAGGAACCGAGATCAAGGGTCCGGTC | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTGGCGTCATCGTCAACAACAAGGGCGAAATGAAAGGCTCCGCCATTACTGGACCCGTT | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCGCAGTCGTCATCGACAACAACGGAGATCCCAAGGGAACCCGTATATTTGGTCCTGTA | 3
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTGCGGTTATTATAGATGACAACGGCAATCCCCGTGGTACACGCATATTTGGACCGGTG | 4
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCGCAGTCGTCATCGACAACAACGGAGATCCCAAGGGACCCCGTATATTTGGTCCTGTA | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTGCGGTAATTATAGATGACAACGGCAATCCCCGTGGTACACGCATATTTGGACCGGTG | 6

**Comment by wwood** [comment]
It's ok, that is the paired analysis. It just names the sample after the forward read file name.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Li Zhihua ***@***.***>
Sent: Sunday, July 24, 2022 4:34:06 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] SingleM result (Issue #93)


Hi,
when "singlem pipe --forward GJ4_1.fq.gz --reverse GJ4_2.fq.gz --otu_table GJ4_otu_table.csv --threads 20 --assignment_method diamond" . The results showed only GJ4_1 in the sample colume of GJ4_otu_table.csvas below. I do not know whether it is OK or just analysis the forward sequences G4_1 sample?

S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCAGTAATTATCACCCCTGAAGGTGAAATGAAAGGCTCAGAAATCAGAGGCCCAGTT | 2
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCAGTGATCATATCTCCTGATGGAGTTTTGAAAGGCTCTGAAATAAGAGGACCAGTG | 21
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAATGGTAATTACGGATGAAGAGGGAGTACCCAAAGGCACGGACATAAAAGGTCCCGTA | 6
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCATGGTAATCACGGATGAAGACGGGATTCCAAAAGGCACGGACATAAAAGGTCCTATA | 40
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCATGGTAATCACGGATGAAGATGGGATTCCCAAAGGCACGGACATAAAAGGTCCTGTA | 10
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTATGGTAATCACGGACGAAGATGGTATTCCCAAAGGGACGGACATAAAAGGTCCTGTA | 4
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCTGTTATACTCTCGACAGATGGAGTGCTTAAGGGTTCTGAAATAAGAGGACCAATA | 14
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCAGTGATCATATCTCCTGATGGAGTTTTGAAAGGCTCTGAAATAAGGGGACCAGTG | 2
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTATGGTAATTACGGATGAAGAGGGAGTACCCAAAGGCACGGACATAAAATGTCCCGTA | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCAGCTGTAATAGTATCCCCTGAGGGTGTACTAAAAGGTTCTGAAATAAGGGGACCAATT | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCATGGTGCTCGTCAACGAGCGCGACGAGCCGAAAGGAACCGAGATCAAGGGTCCGGTC | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTGGCGTCATCGTCAACAACAAGGGCGAAATGAAAGGCTCCGCCATTACTGGACCCGTT | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCGCAGTCGTCATCGACAACAACGGAGATCCCAAGGGAACCCGTATATTTGGTCCTGTA | 3
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTGCGGTTATTATAGATGACAACGGCAATCCCCGTGGTACACGCATATTTGGACCGGTG | 4
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCCGCAGTCGTCATCGACAACAACGGAGATCCCAAGGGACCCCGTATATTTGGTCCTGTA | 1
S1.6.ribosomal_protein_L14b_L23e_rplN | GJ4_1 | GCTGCGGTAATTATAGATGACAACGGCAATCCCCGTGGTACACGCATATTTGGACCGGTG | 6

―
